<?php
/**********************************************************************************
 *  ⚠️  DO NOT EDIT THIS FILE  —  TEMPLATE ONLY                                    *
 *                                                                                 *
 *  File: config-intranet-default.php                                              *
 *                                                                                 *
 *  ➜ This file provides EXAMPLE values.                                           *
 *  ➜ The application will NOT start if you use it as-is (__IS_DEFAULT => true).    *
 *                                                                                 *
 *  ✅ CORRECT SETUP                                                                *
 *  1) Copy this file to "config-intranet.php"                                     *
 *     - Linux/macOS:  cp config-intranet-default.php config-intranet.php          *
 *     - Windows:      copy config-intranet-default.php config-intranet.php        *
 *                                                                                 *
 *  2) EDIT ONLY "config-intranet.php"                                              *
 *     - Open config-intranet.php in your editor                                   *
 *     - Set __IS_DEFAULT => false                                                   *
 *     - Fill in real values (API_BASE, INTERNAL_SHARED_SECRET, etc.)                *
 *                                                                                 *
 *  3) (Recommended) Do not commit config-intranet.php                              *
 *     - Add "config-intranet.php" to .gitignore / .dockerignore                   *
 *                                                                                 *
 *  ℹ️  The application will refuse to start if:                                    *
 *     - "__IS_DEFAULT" is true                                                      *
 *     - "config-intranet.php" is missing                                          *
 *     - "INTERNAL_SHARED_SECRET" looks like a placeholder                         *
 *     - "API_BASE" is empty                                                         *
 *                                                                                 *
 *  🧩 MINIMAL config-intranet.php example (from this template):                   *
 *  --------------------------------------------------------------------------------
 *  <?php
 *  return [
 *      '__IS_DEFAULT' => false,
 *      'API_BASE' => 'http://192.168.100.2:5000',
 *      'INTERNAL_SHARED_SECRET' => 'a-long-strong-secret-here',
 *      // … adjust the rest for your environment …
 *  ];
 *  --------------------------------------------------------------------------------
 *                                                                                 *
 *  🔒 Notes                                                                         *
 *  - INTERNAL_SHARED_SECRET: use a long, high-entropy string (>32 chars).         *
 *  - API_INSECURE_SKIP_VERIFY: keep false in production.                          *
 *  - HCAPTCHA: replace test keys with your production keys.                       *
 *  - TRUSTED_PROXIES: strict list of reverse-proxy IPs/CIDRs.                     *
 *                                                                                 *
 *  ✋ Again: do not edit this file. Copy it → config-intranet.php                  *
 **********************************************************************************/

/**
 * Default template — demo values.
 * The app stops if __IS_DEFAULT === true.
 */
return [
    '__IS_DEFAULT' => true,

    // --- Database (tools module) ---
    // Either set a MySQL DSN:
    //   'DB_DSN'  => 'mysql:host=127.0.0.1;dbname=intranet;charset=utf8mb4',
    //   'DB_USER' => 'intranet',
    //   'DB_PASS' => 'password',
    //
    // Or leave empty and SQLite will be used via DB_PATH:
    'DB_DSN'  => '',
    'DB_USER' => '',
    'DB_PASS' => '',

    // SQLite: file path (PHP must be able to write)
    'DB_PATH' => __DIR__ . '/intranet.sqlite',

    // --- UI / links ---
    // Show "Forgot password?" link (true = on, false = off)
    'FORGOT_PASSWORD_ENABLED' => true,

    // Optional: show client IP in the nav bar
    'SHOW_CLIENT_IP' => true, // or false to hide

    // Site default UI language ("en" or "fr"). Used when switching is off, or as fallback if session has no valid choice.
    'DEFAULT_LANGUAGE' => 'en',

    // If true, users may set language via POST; it is stored only in the PHP session (no intranet_lang cookie).
    // If false, the UI always uses DEFAULT_LANGUAGE; any previous session value is ignored and cleared (no switcher).
    'USER_LANGUAGE_SWITCH_ENABLED' => true,

    // Optional: which UI locales are available (must exist in intranet-i18n-messages.php). Default: fr + en.
    // Example single-language site: ['fr'] — no language switcher is shown.
    // 'UI_LOCALES' => ['fr', 'en'],

    // ===== Network / proxy =====
    // Trusted proxy IPs/CIDRs; CLIENT_IP_HEADER is honored only when the request
    // comes from one of these addresses.
    'TRUSTED_PROXIES' => '192.168.100.32,127.0.0.1,::1',
    'CLIENT_IP_HEADER' => 'X-Forwarded-For',

    // ===== .NET API (ADSelfService_API.Server) =====
    // Backend API base URL (exposes /auth, /users, /admin/*)
    'API_BASE' => 'http://127.0.0.1:5000',

    // Optional: if set, PHP sends the X-Internal-Auth header.
    // ⚠️ PLACEHOLDER — replace in config-intranet.php
    'INTERNAL_SHARED_SECRET' => 'change-me-please-32+chars',

    // Dev only: skip TLS verify if API uses self-signed HTTPS (not for production)
    'API_INSECURE_SKIP_VERIFY' => false,

    // cURL timeout to the LDAP API (seconds, minimum 1)
    'API_LDAP_CURL_TIMEOUT_SEC' => 10,

    // ===== hCaptcha =====
    // Enable captcha on login (and forgot-password if used)
    'HCAPTCHA_ENABLED' => true,
    // Default test keys: SiteKey 10000000-ffff-ffff-ffff-000000000001 / Secret 0x0000...
    'HCAPTCHA_SITEKEY' => '10000000-ffff-ffff-ffff-000000000001',
    'HCAPTCHA_SECRET'  => '0x0000000000000000000000000000000000000000',
    // false only in lab if TLS verification to hcaptcha.com fails (MITM / missing CA)
    'HCAPTCHA_VERIFY_SSL' => true,

    // ===== Browser session (PHPSESSID cookie + lifetime) =====
    // Server-side idle timeout aligned with cookie (minutes, min. 1; default 720 = 12 h)
    'SESSION_LIFETIME_MINUTES' => 720,

    // ===== Intra sync key (session / cookie coupling) =====
    // 0 = no periodic rotation. Otherwise on GET to intranet.php, after N minutes without rotation,
    //     issue a new key in $_SESSION['_key'] and Intra-Sync-Key cookie (same expiry as PHP session).
    'INTRA_SYNC_KEY_ROTATE_MINUTES' => 0,

    // ===== Outbound mail (forgot password, etc.) =====
    // 'internal' = PHP mail() / local SMTP; 'api' = your mailer API (MAILER_API_URL + key)
    'MAIL_MODE' => 'internal',
    // For 'api' mode:
    'MAILER_API_URL' => 'https://example.com/api/private/mailer/mailer.php',
    'MAILER_API_KEY' => '',  // or getenv('MAILER_API_KEY') on the server
    // For 'internal' mode: From address
    'MAIL_FROM' => 'Intranet <no-reply@example.local>',

    // ===== Twilio SMS (forgot password by phone) =====
    // Keep credentials in config (or getenv), never hard-coded in app code.
    'TWILIO_SMS_ENABLED'   => false,
    'TWILIO_ACCOUNT_SID'   => '',  // Twilio account
    'TWILIO_AUTH_TOKEN'    => '',  // or getenv('TWILIO_AUTH_TOKEN')
    'TWILIO_FROM_NUMBER'   => '',  // Sender number (e.g. +33600000000) or Twilio number SID

    // ===== UI / pagination =====
    'ADMIN_LIST_PAGE_SIZE' => 50,

    // ===== Login rate limit (pick one storage backend) =====
    // LOGIN_RL_USE_FILE=true  → logs + blocked.txt on disk (count per IP).
    // LOGIN_RL_USE_FILE=false → APCu if available, else PHP session (count per login+IP).
    // Require WARN_AFTER < BLOCK_AFTER so the warning message can appear before block.
    'LOGIN_RL_ENABLED' => true,
    'LOGIN_RL_USE_FILE' => true,
    'LOGIN_RL_LOG_DIR' => null,              // null = __DIR__ . '/rl_logs' (file mode only)
    'LOGIN_RL_WINDOW_SECONDS' => 1800,       // sliding window (seconds)
    'LOGIN_RL_WARN_AFTER' => 5,              // failures in window → "too many attempts" message
    'LOGIN_RL_BLOCK_AFTER' => 15,            // failures in window → block (IP on disk, or login+IP in memory)
    'LOGIN_RL_MEMORY_BLOCK_SECONDS' => 1200, // block duration in memory mode (seconds); ignored in file mode

    // Groups allowed to manage user accounts
    'ADM_USER_GROUPS'   => ['ADSyncAdmins','UserAdmins'],
    // Groups allowed to manage OUs and groups
    'ADM_DOMAIN_GROUPS' => ['ADSyncAdmins','OUAdmins'],
];
